# Lets us import our file from our computer

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_csv("company_data.csv")
data

,Employee_ID,Employee_Name,Department,Region,Product,Units_Sold,Unit_Price,Revenue,Target,Year
0,1,Employee_1,Procurement,West,Product D,89,690,61410,203088,2026
1,2,Employee_2,Finance,North,Product D,312,739,230568,283673,2024
2,3,Employee_3,Sales,West,Product B,307,597,183279,107455,2025
3,4,Employee_4,Finance,West,Product D,118,665,78470,118066,2026
4,5,Employee_5,Sales,West,Product C,50,278,13900,347417,2025
...,...,...,...,...,...,...,...,...,...,...
495,496,Employee_496,IT,East,Product C,110,436,47960,349542,2025
496,497,Employee_497,Sales,South,Product B,291,646,187986,195834,2024
497,498,Employee_498,IT,North,Product D,237,936,221832,445650,2024
498,499,Employee_499,HR,North,Product E,316,599,189284,146546,2026
499,500,Employee_500,Finance,South,Product E,229,792,181368,348571,2025

# HOW TO GENERATE RAW DATA

In [12]:
# Step1:create a dictionary

data2 = {
    "Employee_ID":[],
    "Employee_Name":[],
    "Department":[],
    "Region":[],
    "Product":[],
    "Units_Sold":[],
    "units_price":[],
    "Revenue":[],
    "Target":[],
    "Year":[]
}

# Create Lists
department = ["Sales", "finance", "HR", "IT", "Procurement"]
region = ["North", "South", "East", "West"]
product = ["Product A", "Product B", "Product C", "Product D", "Product E"]

# create for loop
for i in range(1,501):
    unit = random.randint(10,500)
    price = random.randint(100,1000)
    revenue = unit * price
    
    data2["Employee_ID"].append(f"EMP- {i}"),
    data2["Employee_Name"].append(f"Employee_{i}"),
    data2["Department"].append(random.choice(department)),
    data2["Region"].append(random.choice(region)),
    data2[ "Product"].append(random.choice(product)),
    data2["Units_Sold"].append(unit),
    data2[ "units_price"].append(price),
    data2[ "Revenue"].append(revenue),
    data2["Target"].append(random.randint(100000,500000)),
    data2["Year"].append(random.choice([2024,2025,2026]))



# Create Dataframe
df = pd.DataFrame(data2)
display(df.head())
display(df.tail())

,Employee_ID,Employee_Name,Department,Region,Product,Units_Sold,units_price,Revenue,Target,Year
0,EMP- 1,Employee_1,IT,North,Product A,160,134,21440,333029,2024
1,EMP- 2,Employee_2,finance,North,Product D,195,300,58500,274565,2024
2,EMP- 3,Employee_3,HR,East,Product C,190,649,123310,142597,2025
3,EMP- 4,Employee_4,finance,East,Product E,369,495,182655,476452,2025
4,EMP- 5,Employee_5,finance,North,Product B,32,320,10240,299472,2024

,Employee_ID,Employee_Name,Department,Region,Product,Units_Sold,units_price,Revenue,Target,Year
495,EMP- 496,Employee_496,HR,North,Product C,317,816,258672,211780,2025
496,EMP- 497,Employee_497,Procurement,North,Product D,151,942,142242,222509,2025
497,EMP- 498,Employee_498,Procurement,South,Product A,30,398,11940,204421,2024
498,EMP- 499,Employee_499,IT,South,Product A,213,316,67308,205377,2025
499,EMP- 500,Employee_500,Sales,North,Product B,206,854,175924,418485,2025

#  Step 2: Save and Read Dataset

In [19]:
# Save your Random Data into a csv file
df.to_csv("company_data2.csv", index=False)